In [ ]:
import numpy as np

In [4]:
list=[1,2,3,4,5]
print(list)
nump=np.array(list)
print(nump)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [7]:
b=np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
c=np.linspace(1,10,10)
print(c)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [11]:
d=np.zeros((3,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
e=np.ones((3,3))
print(e)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
f=np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
g=np.diag([1,2,3,4])
print(g)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [16]:
np.random.rand(4) # uniform distribution

array([0.00976896, 0.27447305, 0.95640447, 0.30673713])

In [17]:
np.random.randn(4) # gaussian distribution

array([-0.75409033, -0.58015518, -0.00655162,  0.0882777 ])

In [19]:
b==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [22]:
np.array_equal(b,b)

True

In [23]:
np.array_equal(c,b)

False

In [26]:
b.sum()

45

In [30]:
print(np.logical_or(c,b) )
print(np.sin(b))
print(np.exp(b))
print(np.log(b))

[ True  True  True  True  True  True  True  True  True  True]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


/tmp/ipykernel_239019/1423112441.py:4: RuntimeWarning: divide by zero encountered in log
  print(np.log(b))


In [32]:
print(np.min(b))
print(np.max(b))
print(np.argmin(b))
print(np.argmax(b))

0
9
0
9


In [33]:
np.all(b>0)

False

In [34]:
np.any(b>0)

True

In [37]:
np.median(b) # mode,std

4.5

In [38]:
np.tile([1,2,3],(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [42]:
oneD=np.array([1,2,3,4])
print(oneD)
oneD=oneD[:,np.newaxis]
print(oneD)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


In [43]:
oneD.ravel()

array([1, 2, 3, 4])

In [46]:
np.shape(b)

(10,)

In [48]:
np.reshape(b,(5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [51]:
np.resize(b,(6,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [9, 0, 1],
       [2, 3, 4],
       [5, 6, 7]])