In [10]:
import torch
import numpy as np

 BackPropogation

In [7]:
x=torch.tensor(1.0)
y=torch.tensor(2.0)
w=torch.tensor(1.0, requires_grad=True)

In [8]:
#forward pass
y_hat= w*x
loss= (y-y_hat)**2
print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [9]:
#backward pass
loss.backward()
print(w.grad)

##update weights

tensor(-2.)


GD

In [17]:
x=np.array([1,2,3,4],dtype=np.float32)
y=np.array([2,4,6,8],dtype=np.float32)
w=0.0


def forward(x):
  return w*x

def loss(y,y_pred):
  return ((y-y_pred)**2).mean()

def gradient(x,y,y_pred):
  return np.mean(2*x*(y_pred-y))


print(f'Before training {forward(5)}')


learning_rate=0.01
n_iters=50

for epoch in range(n_iters):
  y_pred=forward(x)
  l=loss(y,y_pred)
  dw=gradient(x,y,y_pred)
  w-=learning_rate*dw

print(f'After training {forward(5)}')


Before training 0.0
After training 9.997042402625084


Using torch

In [20]:
x=torch.tensor([1,2,3,4],dtype=torch.float32)
y=torch.tensor([2,4,6,8],dtype=torch.float32)
w=torch.tensor([0.0],dtype=torch.float32,requires_grad=True)


def forward(x):
  return w*x

def loss(y,y_pred):
  return ((y-y_pred)**2).mean()


print(f'Before training {forward(5)}')


learning_rate=0.01
n_iters=50

for epoch in range(n_iters):
  y_pred=forward(x)
  l=loss(y,y_pred)
  l.backward()
  with torch.no_grad():
    w -= learning_rate * w.grad
    # zero the gradients after updating
    w.grad.zero_()

print(f'After training {forward(5)}')


Before training tensor([0.], grad_fn=<MulBackward0>)
tensor([0., 0., 0., 0.], grad_fn=<MulBackward0>)
tensor([0.3000, 0.6000, 0.9000, 1.2000], grad_fn=<MulBackward0>)
tensor([0.5550, 1.1100, 1.6650, 2.2200], grad_fn=<MulBackward0>)
tensor([0.7717, 1.5435, 2.3152, 3.0870], grad_fn=<MulBackward0>)
tensor([0.9560, 1.9120, 2.8680, 3.8239], grad_fn=<MulBackward0>)
tensor([1.1126, 2.2252, 3.3378, 4.4504], grad_fn=<MulBackward0>)
tensor([1.2457, 2.4914, 3.7371, 4.9828], grad_fn=<MulBackward0>)
tensor([1.3588, 2.7177, 4.0765, 5.4354], grad_fn=<MulBackward0>)
tensor([1.4550, 2.9100, 4.3651, 5.8201], grad_fn=<MulBackward0>)
tensor([1.5368, 3.0735, 4.6103, 6.1471], grad_fn=<MulBackward0>)
tensor([1.6063, 3.2125, 4.8188, 6.4250], grad_fn=<MulBackward0>)
tensor([1.6653, 3.3306, 4.9959, 6.6613], grad_fn=<MulBackward0>)
tensor([1.7155, 3.4310, 5.1465, 6.8621], grad_fn=<MulBackward0>)
tensor([1.7582, 3.5164, 5.2746, 7.0328], grad_fn=<MulBackward0>)
tensor([1.7945, 3.5889, 5.3834, 7.1778], grad_fn=<Mul

In [25]:
import torch
import torch.nn as nn

x = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)


n_samples, n_features = x.shape

x_test = torch.tensor([5], dtype=torch.float32)

input_size = n_features
output_size = n_features


class LinearRegression(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegression, self).__init__()
        # define diferent layers
        self.lin = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        return self.lin(x)

model = LinearRegression(input_size, output_size)

print(f'Prediction before training: f(5) = {model(x_test).item():.3f}')


learning_rate = 0.01
n_iters = 100

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
for epoch in range(n_iters):
    # predict = forward pass with our model
    y_predicted = model(x)

    # loss
    l = loss(y, y_predicted)

    # calculate gradients = backward pass
    l.backward()

    # update weights
    optimizer.step()

    # zero the gradients after updating
    optimizer.zero_grad()

    if epoch % 10 == 0:
        [w, b] = model.parameters() # unpack parameters
        print('epoch ', epoch+1, ': w = ', w[0][0].item(), ' loss = ', l)

print(f'Prediction after training: f(5) = {model(x_test).item():.3f}')


Prediction before training: f(5) = 3.163
epoch  1 : w =  0.6409040093421936  loss =  tensor(11.8180, grad_fn=<MseLossBackward0>)
epoch  11 : w =  1.4318721294403076  loss =  tensor(0.5537, grad_fn=<MseLossBackward0>)
epoch  21 : w =  1.569422960281372  loss =  tensor(0.2478, grad_fn=<MseLossBackward0>)
epoch  31 : w =  1.601567268371582  loss =  tensor(0.2263, grad_fn=<MseLossBackward0>)
epoch  41 : w =  1.6164610385894775  loss =  tensor(0.2130, grad_fn=<MseLossBackward0>)
epoch  51 : w =  1.6282930374145508  loss =  tensor(0.2006, grad_fn=<MseLossBackward0>)
epoch  61 : w =  1.639353632926941  loss =  tensor(0.1889, grad_fn=<MseLossBackward0>)
epoch  71 : w =  1.650019645690918  loss =  tensor(0.1779, grad_fn=<MseLossBackward0>)
epoch  81 : w =  1.6603597402572632  loss =  tensor(0.1675, grad_fn=<MseLossBackward0>)
epoch  91 : w =  1.6703927516937256  loss =  tensor(0.1578, grad_fn=<MseLossBackward0>)
Prediction after training: f(5) = 9.339
